---
- name: Set list of path to look for local GitLab configuration directory
  ansible.builtin.set_fact:
    gitlab_search_config_paths: "{{ gitlab_search_config_paths }} + [ '{{ gitlab_search_config_path }}' ]"
  with_items: "{{ group_names }}"

- name: Check if GitLab configuration directory exists
  ansible.builtin.stat:
    path: "{{ item }}"
  register: gitlab_config_check
  become: false
  delegate_to: 127.0.0.1
  with_first_found:
    - files: "{{ gitlab_search_config_paths }}"
      skip: true

- name: Set GitLab configuration directory
  ansible.builtin.set_fact:
    gitlab_host_config_path: "{{ gitlab_config_check.results[0].stat.path }}"
  when:
    - gitlab_config_check.results[0] is defined
    - gitlab_config_check.results[0].stat is defined
    - gitlab_config_check.results[0].stat.isdir

- name: Check if GitLab template configuration file is exists
  ansible.builtin.stat:
    path: "{{ gitlab_host_config_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: gitlab_config_check

- name: Check if GitLab SSL certificates is exists
  ansible.builtin.stat:
    path: "{{ gitlab_host_config_ssl_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: gitlab_config_ssl_check
